[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.95

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true
primary.background = "#1F1F28" # Kanagawa default background color

[keyboard]
bindings = [
	{ key = "Space", mods = "Control", chars = "\u0000" },
]
